### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by ibnabbas** [geissbuehler/TermservPatcher#8]
I am getting error as below:

Error: No match in termsrv.dll found for manual patch patterns
Scheduled task 'TermsrvPatcher' added (requires valid patches in 'Patches.txt', logging to 'UnattendLog.txt')

Patcher Version - 1.3.0

termsrv.dll Version: 10.0.19041.1

**Comment by geissbuehler** [comment]
Duplicate of #1
